name: 编译内核a14-6-1

permissions:
  contents: write
  actions: write
  
on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: "选择 KernelSU"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "选择 ksu 分支"
        required: true
        type: choice
        options:
          - "Stable(标准)"
          - "Dev(开发)"
          - "Other(其他/指定)"
        default: "Stable(标准)"
      version:
        description: "自定义版本名(如6.1.93后面的字符/留空则使用默认版本号)"
        required: true
        type: string
        default: "-android14-11-gca0ef6d17716-ab13624819"
      build_time:
        description: "设置内核构建时间(格式见仓库说明)"
        required: true
        type: string
        default: "Tue Jun 10 18:59:08 UTC 2025"
      lz4_upd:
        description: "升级LZ4算法至1.10.0?"
        required: true
        type: boolean
        default: true
      more_zram_kpm:
        description: "是否启用更多ZRAM算法以及KPM功能?"
        required: false
        type: boolean
        default: false
      use_O2:
        description: "是否开启O2编译优化?"
        required: true
        type: boolean
        default: true
      BBG:
        description: "是否启用内核层面阻止对关键分区/设备节点的非法写入(LSM)?"
        required: true
        type: boolean
        default: true
      set_defbbr:
        description: "是否将BBR设为默认拥塞算法?（实验性）"
        required: true
        type: boolean
        default: true
      rekernel_enable:
        description: "添加Re:Kernel支持?"
        required: true
        type: boolean
        default: true

jobs:
  build-kernel-a14-6-1:
    uses: ./.github/workflows/kernel-a14-6.1.yml
    secrets: inherit
    with:
      make_release: false
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ inputs.version }}
      lz4_upd: ${{ inputs.lz4_upd }}
      more_zram_kpm: ${{ inputs.more_zram_kpm }}
      use_O2: ${{ inputs.use_O2 }}
      BBG: ${{ inputs.BBG }}
      set_defbbr: ${{ inputs.set_defbbr }}
      rekernel_enable: ${{ inputs.rekernel_enable }}
      build_time: ${{ inputs.build_time }}
