name: Android 14 6.1
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
    inputs:
      make_release:
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        required: true
        type: string
        default: Next
      kernelsu_branch:
        required: true
        type: string
        default: Stable
      version:
        required: true
        type: string
        default: "-android14-11-gca0ef6d17716-ab13624819"
      lz4_upd:
        description: '升级LZ4算法至1.10.0?'
        required: true
        type: boolean
        default: true
      more_zram_kpm:
        description: '启用更多ZRAM算法和KPM功能?'
        required: false
        type: boolean
        default: false
      use_O2:
        description: '是否开启O2编译优化?'
        required: true
        type: boolean
        default: true
      BBG:
        description: '是否启用BBG防格机补丁？'
        required: true
        type: boolean
        default: true
      set_defbbr:
        description: '是否将BBR设为默认拥塞算法?（实验性）'
        required: true
        type: boolean
        default: true
      rekernel_enable:
        description: '添加Re:Kernel支持?'
        required: true
        type: boolean
        default: true
      build_time:
        description: '设置内核构建时间(格式见仓库说明)'
        required: true
        type: string
        default: "Tue Jun 10 18:59:08 UTC 2025"
        
jobs:
  build-kernel-a14-6-1-kernelsu-susfs:
    strategy:
      fail-fast: false
      matrix:
        include:
          #- sub_level: "25"
          #  os_patch_level: "2023-10"
          #- sub_level: "43"
          #  os_patch_level: "2023-11"
          #- sub_level: "57"
          #  os_patch_level: "2024-01"
          #- sub_level: "68"
          #  os_patch_level: "2024-03"
          #- sub_level: "75"
          #  os_patch_level: "2024-05"
          #- sub_level: "78"
          #  os_patch_level: "2024-06"
          #- sub_level: "84"
          #  os_patch_level: "2024-07"
          #- sub_level: "90"
          #  os_patch_level: "2024-08"
          #- sub_level: "93"
          #  os_patch_level: "2024-09"
          #- sub_level: "99"
          #  os_patch_level: "2024-10"
          #- sub_level: "112"
          #  os_patch_level: "2024-11"
          #- sub_level: "115"
          #  os_patch_level: "2024-12"
          - sub_level: "118"
            os_patch_level: "2025-01"
          #- sub_level: "124"
          #  os_patch_level: "2025-02"
          #- sub_level: "128"
          #  os_patch_level: "2025-03"
          #- sub_level: "129"
          #  os_patch_level: "2025-04"
          #- sub_level: "134"
          #  os_patch_level: "2025-05"
          #- sub_level: "145"
          #  os_patch_level: "2025-09"
          #- sub_level: "X"
          #  os_patch_level: "lts"
    uses: ./.github/workflows/gki-kernel.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release || false }}
      android_version: "android14"
      kernel_version: "6.1"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant || 'Next' }}
      kernelsu_branch: ${{ inputs.kernelsu_branch || 'Dev' }}
      version: ${{ inputs.version }}
      lz4_upd: ${{ inputs.lz4_upd }}
      more_zram_kpm: ${{ inputs.more_zram_kpm }}
      use_O2: ${{ inputs.use_O2 || false }}
      supp_op: ${{ inputs.supp_op || false }}
      BBG: ${{ inputs.BBG }}
      set_defbbr: ${{ inputs.set_defbbr }}
      rekernel_enable: ${{ inputs.rekernel_enable }}
      build_time: ${{ inputs.build_time }}
